export enum Genre {
    ADVENTURE = 'ADVENTURE',
    HISTORICAL_FICTION = 'HISTORICAL_FICTION',
    SCIENCE_FICTION = 'SCIENCE_FICTION',
    FANTASY = 'FANTASY',
    THRILLER = 'THRILLER',
    ROMANCE = 'ROMANCE',
    MYSTERY = 'MYSTERY',
    NON_FICTION = 'NON_FICTION',
    BIOGRAPHY = 'BIOGRAPHY',
    CHILDREN = 'CHILDREN',
    YOUNG_ADULT = 'YOUNG_ADULT',
    HORROR = 'HORROR',
    DRAMA = 'DRAMA',
  }
  